### ISSUE TITLE
Mountaineers 2022 Gala Live Auction Items

### ISSUE THREAD

**Issue by msimerson** [MeanyLodge/Committee#21]
### Snowmobile-assisted backcountry ski day

Hi Dave and Matt, We're in the process of firming up our auction packages for the Apr 2 gala and I had an idea. What would you think about offering a guided, snowmobile-assisted BC skiing adventure out of Meany? My sense is that we'd end up with a bidding war. In the past, one-of-a-kind, adventure experiences have been the most popular items so something like this could get a lot of interest. -- Tom Vogl

Art (wearing his BC ski leader badge) and another volunteer who’s comfortable leading trips on the snowmobile (likely Dave or Matt) will lead a day of skiing in the Meany backcountry for one. The winner must have some backcountry ski experience and provide their own gear. The outing would be scheduled for a mutually agreeable date between 11/1/22 – 4/1/23. I can offer more language and suggested restrictions, but my thinking is to keep this opportunity tailored to those who can already ski vs. incorporating a ski lesson. -- Amber

> As long as Matt or Dave are in, I will certainly be happy to participate. -- Art
> If the powder is good, there’s certainly a lot of terrain we could take people to via snowmobile hops, and I’d be up for driving or skiing it. -- Dave
> I'm in!  We can tailor the excursion to fit the abilities and interests of the participants. For babes in the wool, we take them down Nicky's Trail and use the snowmobiles to bring them back up the hill. If they've taken the Uphill Travel course or similar, then we'll take them off campus on something that will appropriately challenge them AND be fun. If the winner(s) have AIRIE 1 or better and some experience in the BC, we can level up. -- Matt
>
>> We could offer a menu of BC experiences:
>> a. Easy. A Saturday with Art & Dave's BC intro. Then experience a 3-4 mile mini-adventure.
>> a1. A trek over to Stampede Pass with a mixture of groomed forest roads and not-so-rugged backcountry terrain.
>> a2. NIki's Trail and back via the Palouse to Cascades / John Wayne.
>>
>> b. Moderate. 5-8 miles.
>> b1. A round trip up to the Telephone Cabin, past the Stampede weather station, and then back home with a snowmobile tow up from skier pickup.
>> b2. Climb the Meany hill, continue up to Mt. Francis via the power line slot. Loop around the top and then ski home via the slots in Walt's Woods.
>> 
>> c. Extreme. 10-20 miles.
>> c1. Up Meany hill, ascend to the Saddle, then ski the glades until everyone is exhausted. The South glade if the snow is bad, the East facing glade when the snow is delicious. Then ski down the 4100 road back to the lodge.
>> c2. Last year, 8 of us ski-towed up to Yakima Pass and were dropped off for a ski home to Meany. That's the more pleasant half of the Patrol Race route but can still consume an entire day.
>> c3. A guided ski of the Patrol Race route. Last year Nigel and I guided two of the ladies race teams along the route as part of their training. For new teams, the route is unfamiliar, remote and rugged. Having guides with radios and snowmobiles at the ready would be a valuable service. -- matt

- [x] Name: Snowmobile-assisted backcountry ski day
- [x] Estimated Value: $500
- [x] Description:  A guided, snowmobile-assisted BC skiing adventure out of Meany for up to 4 persons. The winner and attendees must have backcountry ski experience and provide their own gear. Meany Lodge will provide snowmobile transportation to and from the Crystal Springs Sno-Park to a BC skiing destination that suites the winners abilities, level of interest, and weather conditions.
- [x] Restrictions: a mutually agreeable date between 11/1/22 – 4/1/23. A parking pass is required to park at Crystal Springs Sno-Park.

### Snow Groomer Driving Lesson

- [x] TODO: Ask Dave C
- [x] Name: Snow Groomer Driving Lesson
- [x] Estimated Value: $600
- [x] Description: Go for a ride in, and then learn to drive a snow groomer.
- [x] Restrictions: to take place on a regular grooming day (F,Sat,Sun) or as mutually agreeable.

### Guaranteed Mushroom Weekend reservation

- [x] Name: Guaranteed Mushroom Weekend reservation
- [x] Estimated Value: $300
- [x] Description: A guaranteed reservation for 2 persons to Meany Mushroom Weekend. You don't have to wait until tickets go on sale and rush to buy one before they sell out!
- [x] Restrictions: none.

### Private Pow Party on the Meany ski hill

- [x] Name: Private Pow Party on the Meany ski hill
- [x] Estimated Value: $750
- [x] Description: Up to 10 skiers/boarders get a private day on the Meany ski hill.  The experience is to be scheduled for a mutually agreeable weekday between 11/1/2022 and 4/1/2023. Meany Lodge volunteers will transport you and your guests 3 miles from the Crystal Springs Sno-Park to the lodge. After you've skied your fill, we'll take you back out to the Sno-Park. With 3 days notice, we can muster additional volunteers to also open the lodge and provide a hot cooked meal.
- [x] Restrictions: between 11/1/2022 and 4/1/2023 with 3 days notice. A pass is required to park at Crystal Springs Sno-Park.

Art [Freeman] and I [Amber Carrigan] both think this opportunity has the potential to be wildly successful and lucrative. Who doesn’t want access to their own ski hill?! To ensure this experience is easy to facilitate, we’d keep our offerings rooted in the ski experience. We’re thinking the winner could invite X friends ( # to be determined by the volunteers facilitating the experience) to spend X hours (# to be determined by the volunteers facilitating the experience) on the Meany ski hill for a private ski day. The experience would be scheduled for a mutually agreeable weekday between 11/1/22 – 4/1/23. I don’t think we need to open the lodge for this experience to be a great one for the winner – we can focus more on skiing and less on food/lodging.

#### The Need for PPP

1. one transport operator
2. one tow operator
3. a lodge opener who can drop and hang the ropes
 and potentially:
4. a lodge host (opener/closer)
5. a cook

#### Volunteers for PPP

- Art - BC leader / instructor
- Maud - transport, host, cook, ski instructor, BC enthusiast
- Nigel - transport, ski enthusiast / guide
- Bev - transport, tow op, host, cook, XC ski leader
- Suzette - cook
- Matt - transport, host, cook, BC enthusiast
- Dan N - transport, tow op, ski instructor
- Chuck - transport, tow op, host
- Jim F - transport, tow op, host, ski instructor

#### Comments

- We should have at least 2 committee to 'escort' guests into the backside -- Chuck
- The magic bullet is aligning the purchaser's schedule with a weekday powder day. -- Nigel
- Could we put in the possibility of a ski clinic (as part of the win)? -- Dan

**Comment by ecwelter** [comment]
Folks
I have looked over our past records and can only find that the Groomer Driving less  we offered in 2012 went for $600.  Can't tell who bought it or if it was ever actually delivered.

Regarding the BC experiences:
Guests also need their own parking credential for CS parking lot, unless that Carpool with committee
I think that we could offer all 3 experiences at $100/person for Easy, $200/person for Moderate and $300/person for Extreme.  I think the limit for these groups ought to be 4-6.  I think we'd want to have committee and 2 snowmobiles standing by just in cast they're needed for support.

Mushroom Weekend
Maybe $300 for reservation for 2.  We have lots of couples coming to mushroom weekend.

Private Pow Party
I think we could offer this for up to 10 skier/boarders with bids starting at $750.  And I'd like to see a 3 day notice for both lodge and trip.  

Let me know what else I can do to help.
Cheers

**Comment by msimerson** [comment]
Thanks Chuck!  I've merged in all your suggestions except related to BC. We need to discuss that more with Art & Dave. The menu of options may not be workable due to weather and avy conditions, skier abilities, and the like. Having a menu is good, but I suspect that selling a generic package is better, and we leave negotiating the details up to the trip leader.

**Comment by msimerson** [comment]
# Updated language from Sarah

### Title: Snowmobile-Assisted Backcountry Ski Day and evo
 
Description:
Share a day in a backcountry winter wonderland with your closest family and friends! This package includes a guided, snowmobile-assisted backcountry skiing adventure for up to four people. After parking at the Crystal Springs Sno-Park, Meany Lodge volunteers will transport you and your party via snowmobile to a backcountry skiing destination that best suits the skier's abilities and interests, and where the snow is promised to be the best that day. 
 
In addition to a beautiful day in the backcountry, the winner will receive a $1,000 gift card to evo, a premier outdoor retailer for all things snowsports! Whether you need a new helmet, the latest pair of bibs, or some mountain gear that transitions smoothly to your après-ski, evo has you covered. You will also be receiving a copy of [The Man Behind the Maps](https://jamesniehues.com/pages/the-man-behind-the-map), by James Niehues, featuring over 200 ski resort trail maps hand-painted by the legendary artist, as well as a copy of [Staying Alive in Avalanche Terrain](https://www.mountaineers.org/books/books/staying-alive-in-avalanche-terrain-3rd-edition), 3rd Edition, by Bruce Tremper, published by Mountaineers Books - a book of great utility for the backcountry aficionado! With your new gear, new books, and a day away with family and friends, you may never want to return to the frontcountry again. 
 
Included in this Package:
(1) Guided snowmobile-assisted backcountry skiing adventure for four, out of Meany Lodge
(1) $1,000 gift card to evo
(1) Copy of The Man Behind the Maps, by James Niehues
(1) Copy of Staying Alive in Avalanche Terrain, 3rd Edition, by Bruce Tremper, published by Mountaineers Books
 
Restrictions:
*The winner and their guests must have backcountry ski experience and provide their own gear. Date must be mutually agreed upon. Valid through April 30, 2023.

### Private Pow Party at Meany Lodge Ski Hill for Ten 
 
Description:
Home to the longest and fastest legally-operated rope tow in the country, our own Meany Lodge offers the mountain escape you need right now. Enjoy the ample acreage with nine of your best ski buddies to redefine the phrase “no friends on a powder day.” You can ski all day, and still have fresh pow left over for tomorrow.
 
Never ridden a rope tow before? No problem. Our volunteers will get you equipped with the proper gear to ride safely and efficiently. Did we mention the rope tow will go as fast as a brisk 17mph? (In truth it can go 19mph, but due to safety regulations we had to put a governor on it.) Experiencing the thrill of being whisked up the hill is a once-in-a-lifetime opportunity, and you don’t want to miss out. 
 
Be sure to grab your new pairs of Spy+ goggles to shield your eyes from the sunny slopes. Once your legs are shaky from all the up-and-down, hitch a ride on the famed Meany sno-cat back to your car at the Crystal Springs Sno-Park. It’s been a great day! 
 
Included in this Package:
(1) Private Pow Party on the Meany ski hill for ten
(2) Spy+ Zac Hale Marauder snow goggles
 
Restrictions:
*Pow Party at Meany Lodge must take place on a mutually agreed upon weekday and is available for up to 10 individuals. All guests must adhere to the Meany Lodge rules and regulations found [here](https://www.mountaineers.org/locations-lodges/meany-lodge). Valid through April 2, 2023.
